### ISSUE TITLE
Elementor's popup is not working in amp using amp enhancer.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/amp-enhancer#54]
Elementor's popup is not working in amp using amp enhancer.

Help scout link - https://secure.helpscout.net/conversation/1504210242/194821?folderId=4459751

**Comment by Enricobt** [comment]
I know that Elementor is not compatible with AMP and usually is not enabled within it. But I found that AMP-Enhancer plugin should allow Elementor execution even with AMP. Unfortunately, I cannot see my POPUPs created by Elementor on mobiles as I see them on laptops.
Hopefully, you can find a solution.

**Comment by Zabi09** [comment]
Pushed in 1.0.45
