### ISSUE TITLE
Class 'Amp_Enhancer_Elementor_Support\Widgets\Plugin' not found

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [ahmedkaludi/amp-enhancer#68]
Error thrown
Class 'Amp_Enhancer_Elementor_Support\Widgets\Plugin' not found

![image](https://user-images.githubusercontent.com/20210961/133906729-3d2b2778-2044-419a-8017-bc7895d24ea7.png)

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/amp_enhancer_elementor_support/#post-14910137

**Comment by Sanjeevsetu** [comment]
Hi @ayoubkhan558-zz

This class is not there inside our plugin. Try our latest version and If You still get this error please create a new ticket. I am closing it
