### ISSUE TITLE
Activating AMP enhancer shows wrong message

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/amp-enhancer#70]
When we activate AMP enhancer it shows a wrong message of failed to prepare AMP page.

Reference Ticket -: https://secure.helpscout.net/conversation/1732435176/220426?folderId=1060554
Reference screenshot -: 
![Screenshot (157)](https://user-images.githubusercontent.com/78167698/147350423-4723108e-0d41-4187-9128-d664be1ee4e7.png)

**Comment by akshaywali** [comment]
Our plugin is working properly with the AMP plugin and this issue can not be recreated. We will closing this ticket for now.
