### ISSUE TITLE
Fatal Error with WooCommerce.

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/amp-enhancer#72]
https://wordpress.org/support/topic/fails-to-prepare-amp-page-in-woo-commerce/
https://wordpress.org/support/topic/fatal-error-with-woocommerce-9/
https://wordpress.org/support/topic/bugs-when-working-with-the-new-version-of-amp-2-2-1/
https://wordpress.org/support/topic/google-search-console-5xx-error/

**Comment by Sanjeevsetu** [comment]
This was fixed.
