### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/amp-enhancer#76]
Ref: https://prnt.sc/Tjs8ZYVRES3f

https://wordpress.org/support/topic/got-error-when-enable-this-plugin/

Error message: Uncaught ReflectionException: Method get_site_editor_type does not exist in amp-enhancer/pagebuilders/elementor/themebuilder/theme-document.php:48](/amp-enhancer/pagebuilders/elementor/themebuilder/theme-document.php:48)

**Comment by akshaywali** [comment]
pushed in update 1.0.48
